services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  react:
    build: ./React
    restart: always
    volumes:
      - ./React/vol/app:/vol/app
      - ./Common:/vol/Common
    
  nest:
    build: ./Nest
    restart: always
    volumes:
      - ./Nest/vol/app:/vol/app
      - ./Common:/vol/Common
    ports:
      - 4000:4000
    expose:
      - 4000:4000

  proxy:
    build: ./Proxy
    restart: always
    ports:
      - 80:80
      - 443:443

