services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  react:
    build: ./React
    restart: always
    volumes:
      - ./react/vol:/vol
    ports:
      - 3000:3000
    
  nest:
    build: ./Nest
    restart: always
    volumes:
      - ./Nest/vol:/vol